version: "2"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8096:8096"
    environment:
        REVERSE_PROXY_DOMAIN_NAME: ${REVERSE_PROXY_DOMAIN_NAME}
    depends_on:
      - gitlab

  jenkins:
    image: ivaprag/jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - cd-code:/var/jenkins_home/workspace/

  mattermost:
    image: mattermost/mattermost-prod-app:3.9.0
    environment:
      MATTERMOST_ENABLE_SSL: "false"
      DB_HOST: db
      MM_DBNAME: mattermost
      MM_USERNAME: mattermost
      MM_PASSWORD: mattermost
    depends_on:
      - db
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-config:/mattermost/config

  owncloud:
    image: owncloud
    volumes:
      - owncloud-data:/var/www/html/data
      - owncloud-config:/var/www/html/config
      - owncloud-apps:/var/www/html/apps

  db:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  fitnesse:
    image: ivaprag/fitnesse
    volumes:
      - fitnesse-data:/opt/fitnesse/FitNesseRoot 
      - cd-code:/opt/fitnesse/workspace

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  gitlab:
    image: sameersbn/gitlab:9.4.1
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false
      - DB_ADAPTER=postgresql
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=gitlab
      - GITLAB_HOST=gitlab
      - GITLAB_PORT=80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string
    volumes:
      - gitlab-data:/home/git/data:Z

volumes:
  jenkins-data:
    driver: local
  mattermost-data:
    driver: local
  mattermost-config:
    driver: local
  owncloud-data:
    driver: local
  owncloud-config:
    driver: local
  owncloud-apps:
    driver: local
  db-data:
    driver: local
  fitnesse-data:
    driver: local
  redis-data:
    driver: local
  gitlab-data:
    driver: local
  cd-code:
    driver: local
